<?php

namespace Database\Seeders;

use App\Models\Unit;
use Illuminate\Database\Seeder;

class UnitSeeder extends Seeder
{
    public function run(): void
    {
        $units = [
            [
                'no_urut' => 1,
                'code_unit' => 'EX-201',
                'hm' => 4520.5,
                'model' => 'PC200-8',
                'sn_chassis' => 'KMTC2008X01923',
                'engine_model' => 'SAA6D107E-1',
                'sn_engine' => 'ENG-88219',
                'engine_make' => 'Komatsu',
                'equipment_capacity' => '0.93 m3',
                'no_police' => '-',
                'attachments' => 'Standard Bucket',
                'hp' => '148 HP',
                'kw' => '110 KW',
                'tahun_perakitan' => 2022,
                'received_date' => '2022-03-15',
                'received_from' => 'United Tractors Jakarta',
                'location' => 'Site Sangatta',
                'before_from' => 'Workshop Balikpapan',
                'remarks' => 'Unit siap operasi, performa hidrolik normal',
                'status' => 'Operational',
            ],
            [
                'no_urut' => 2,
                'code_unit' => 'DT-101',
                'hm' => 8140.0,
                'model' => 'HD785-7',
                'sn_chassis' => 'KMTD7857X02102',
                'engine_model' => 'SAA12V140E-3',
                'sn_engine' => 'ENG-99120',
                'engine_make' => 'Komatsu',
                'equipment_capacity' => '60 m3 / 91 Ton',
                'no_police' => 'KT 8192 UT',
                'attachments' => 'Dump Body Heavy Duty',
                'hp' => '1178 HP',
                'kw' => '879 KW',
                'tahun_perakitan' => 2021,
                'received_date' => '2021-06-20',
                'received_from' => 'UT Balikpapan',
                'location' => 'Pit Central',
                'before_from' => 'New Unit Delivery',
                'remarks' => 'Rutin servis 250 jam, tyre kondisi 85%',
                'status' => 'Operational',
            ],
            [
                'no_urut' => 3,
                'code_unit' => 'DZ-005',
                'hm' => 6320.2,
                'model' => 'D85ESS-2',
                'sn_chassis' => 'KMTD85ESX05432',
                'engine_model' => 'SA6D125E-2',
                'sn_engine' => 'ENG-77312',
                'engine_make' => 'Komatsu',
                'equipment_capacity' => '3.4 m3 Blade',
                'no_police' => '-',
                'attachments' => 'Straight Tilt Dozer Blade',
                'hp' => '200 HP',
                'kw' => '149 KW',
                'tahun_perakitan' => 2020,
                'received_date' => '2020-09-10',
                'received_from' => 'Workshop Samarinda',
                'location' => 'Workshop Central',
                'before_from' => 'Site Sangatta Pit 1',
                'remarks' => 'Menunggu spare part seal cylinder lift',
                'status' => 'Breakdown',
            ],
            [
                'no_urut' => 4,
                'code_unit' => 'WL-012',
                'hm' => 5120.0,
                'model' => 'CAT 966H',
                'sn_chassis' => 'CAT966HX12891',
                'engine_model' => 'C11 ACERT',
                'sn_engine' => 'ENG-55410',
                'engine_make' => 'Caterpillar',
                'equipment_capacity' => '4.2 m3',
                'no_police' => '-',
                'attachments' => 'General Purpose Bucket',
                'hp' => '262 HP',
                'kw' => '195 KW',
                'tahun_perakitan' => 2023,
                'received_date' => '2023-01-25',
                'received_from' => 'Trakindo Utama',
                'location' => 'Port Loading Area',
                'before_from' => 'New Unit Delivery',
                'remarks' => 'Sedang pengerjaan PM 500 jam',
                'status' => 'Maintenance',
            ],
            [
                'no_urut' => 5,
                'code_unit' => 'MG-003',
                'hm' => 3890.5,
                'model' => 'GD705A-4',
                'sn_chassis' => 'KMTGD705X03321',
                'engine_model' => 'SAA6D114E-3',
                'sn_engine' => 'ENG-66321',
                'engine_make' => 'Komatsu',
                'equipment_capacity' => '4.3 m Moldboard',
                'no_police' => '-',
                'attachments' => 'Blade 14ft & Ripper',
                'hp' => '200 HP',
                'kw' => '149 KW',
                'tahun_perakitan' => 2023,
                'received_date' => '2023-04-12',
                'received_from' => 'UT Sangatta',
                'location' => 'Hauling Road KM 12',
                'before_from' => 'Site Batuta',
                'remarks' => 'Standby menunggu rotasi operator',
                'status' => 'Standby',
            ],
        ];

        foreach ($units as $unit) {
            Unit::updateOrCreate(['code_unit' => $unit['code_unit']], $unit);
        }
    }
}
