<?php

namespace App\Http\Controllers;

use App\Models\Unit;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Inertia\Inertia;

class KpiController extends Controller
{
    public function index(Request $request)
    {
        $month = $request->input('month', Carbon::now()->format('Y-m'));
        $paPlan = (float) $request->input('target_pa', 92);

        // 1. Data Matriks PA Unit (Sesuai Gambar 1)
        $paUnitMatrix = [
            'summary' => [
                'category' => 'PA UNIT',
                'w1' => ['plan' => 92, 'actual' => 96, 'achv' => 94],
                'w2' => ['plan' => 91, 'actual' => 98, 'achv' => 100],
                'w3' => ['plan' => 93, 'actual' => 93, 'achv' => 96],
                'w4' => ['plan' => 92, 'actual' => 88, 'achv' => 93],
                'w5' => ['plan' => 92, 'actual' => 86, 'achv' => 88],
                'trend' => ['plan_mtd' => 92, 'actual' => 92, 'achv' => 97],
                'monthly' => ['budget_running' => 92, 'actual' => '#DIV/0!', 'achv' => 97],
            ],
            'categories' => [
                [
                    'category' => 'EXCAVATOR SMALLER',
                    'w1' => ['plan' => 94, 'actual' => 100, 'achv' => 100],
                    'w2' => ['plan' => 93, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 94, 'actual' => 97, 'achv' => 100],
                    'w4' => ['plan' => 93, 'actual' => 98, 'achv' => 100],
                    'w5' => ['plan' => 93, 'actual' => 97, 'achv' => 100],
                    'trend' => ['plan_mtd' => 93, 'actual' => 98, 'achv' => 100],
                    'monthly' => ['budget_running' => 93, 'actual' => 98, 'achv' => 100],
                ],
                [
                    'category' => 'EXCAVATOR BIGGER',
                    'w1' => ['plan' => 93, 'actual' => 100, 'achv' => 100],
                    'w2' => ['plan' => 91, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 93, 'actual' => 100, 'achv' => 100],
                    'w4' => ['plan' => 91, 'actual' => 92, 'achv' => 100],
                    'w5' => ['plan' => 93, 'actual' => 99, 'achv' => 100],
                    'trend' => ['plan_mtd' => 92, 'actual' => 98, 'achv' => 100],
                    'monthly' => ['budget_running' => 92, 'actual' => 98, 'achv' => 100],
                ],
                [
                    'category' => 'EXCAVATOR CRUSHER',
                    'w1' => ['plan' => 92, 'actual' => 100, 'achv' => 100],
                    'w2' => ['plan' => 92, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 92, 'actual' => 100, 'achv' => 100],
                    'w4' => ['plan' => 92, 'actual' => 61, 'achv' => 66],
                    'w5' => ['plan' => 91, 'actual' => 0, 'achv' => 0],
                    'trend' => ['plan_mtd' => 92, 'actual' => 72, 'achv' => 78],
                    'monthly' => ['budget_running' => 92, 'actual' => 72, 'achv' => 78],
                ],
                [
                    'category' => 'BULLDOZER SMALLER',
                    'w1' => ['plan' => 81, 'actual' => 100, 'achv' => 100],
                    'w2' => ['plan' => 83, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 92, 'actual' => 93, 'achv' => 100],
                    'w4' => ['plan' => 92, 'actual' => 97, 'achv' => 100],
                    'w5' => ['plan' => 93, 'actual' => 98, 'achv' => 100],
                    'trend' => ['plan_mtd' => 88, 'actual' => 97, 'achv' => 100],
                    'monthly' => ['budget_running' => 88, 'actual' => 97, 'achv' => 100],
                ],
                [
                    'category' => 'GRADER CAT',
                    'w1' => ['plan' => 92, 'actual' => 100, 'achv' => 100],
                    'w2' => ['plan' => 91, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 92, 'actual' => 100, 'achv' => 100],
                    'w4' => ['plan' => 91, 'actual' => 99, 'achv' => 100],
                    'w5' => ['plan' => 92, 'actual' => 97, 'achv' => 100],
                    'trend' => ['plan_mtd' => 92, 'actual' => 100, 'achv' => 100],
                    'monthly' => ['budget_running' => 92, 'actual' => 99, 'achv' => 100],
                ],
                [
                    'category' => 'GRADER SEM',
                    'w1' => ['plan' => 94, 'actual' => 91, 'achv' => 97],
                    'w2' => ['plan' => 92, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 94, 'actual' => 84, 'achv' => 90],
                    'w4' => ['plan' => 92, 'actual' => 97, 'achv' => 100],
                    'w5' => ['plan' => 94, 'actual' => 100, 'achv' => 100],
                    'trend' => ['plan_mtd' => 93, 'actual' => 94, 'achv' => 100],
                    'monthly' => ['budget_running' => 93, 'actual' => 94, 'achv' => 100],
                ],
                [
                    'category' => 'GRADER KOMATSU',
                    'w1' => ['plan' => 92, 'actual' => 97, 'achv' => 100],
                    'w2' => ['plan' => 94, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 92, 'actual' => 94, 'achv' => 100],
                    'w4' => ['plan' => 94, 'actual' => 96, 'achv' => 100],
                    'w5' => ['plan' => 90, 'actual' => 98, 'achv' => 100],
                    'trend' => ['plan_mtd' => 92, 'actual' => 97, 'achv' => 100],
                    'monthly' => ['budget_running' => 92, 'actual' => 97, 'achv' => 100],
                ],
                [
                    'category' => 'HAULER CAT 773E',
                    'w1' => ['plan' => 88, 'actual' => 100, 'achv' => 100],
                    'w2' => ['plan' => 88, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 88, 'actual' => 100, 'achv' => 100],
                    'w4' => ['plan' => 88, 'actual' => 86, 'achv' => 98],
                    'w5' => ['plan' => 89, 'actual' => 63, 'achv' => 71],
                    'trend' => ['plan_mtd' => 88, 'actual' => 89, 'achv' => 100],
                    'monthly' => ['budget_running' => 88, 'actual' => 89, 'achv' => 100],
                ],
                [
                    'category' => 'DUMP TRUCK',
                    'w1' => ['plan' => 92, 'actual' => 88, 'achv' => 95],
                    'w2' => ['plan' => 92, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 92, 'actual' => 83, 'achv' => 89],
                    'w4' => ['plan' => 92, 'actual' => 81, 'achv' => 88],
                    'w5' => ['plan' => 92, 'actual' => 81, 'achv' => 88],
                    'trend' => ['plan_mtd' => 92, 'actual' => 86, 'achv' => 93],
                    'monthly' => ['budget_running' => 92, 'actual' => 86, 'achv' => 93],
                ],
                [
                    'category' => 'COMPACTOR',
                    'w1' => ['plan' => 95, 'actual' => 99, 'achv' => 100],
                    'w2' => ['plan' => 93, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 95, 'actual' => 92, 'achv' => 97],
                    'w4' => ['plan' => 93, 'actual' => 98, 'achv' => 100],
                    'w5' => ['plan' => 95, 'actual' => 99, 'achv' => 100],
                    'trend' => ['plan_mtd' => 94, 'actual' => 97, 'achv' => 100],
                    'monthly' => ['budget_running' => 94, 'actual' => 97, 'achv' => 100],
                ],
                [
                    'category' => 'SUPPORT WT',
                    'w1' => ['plan' => 93, 'actual' => 80, 'achv' => 86],
                    'w2' => ['plan' => 92, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 93, 'actual' => 75, 'achv' => 81],
                    'w4' => ['plan' => 92, 'actual' => 71, 'achv' => 77],
                    'w5' => ['plan' => 92, 'actual' => 100, 'achv' => 100],
                    'trend' => ['plan_mtd' => 93, 'actual' => 85, 'achv' => 92],
                    'monthly' => ['budget_running' => 93, 'actual' => 85, 'achv' => 92],
                ],
                [
                    'category' => 'WATER PUMP',
                    'w1' => ['plan' => 93, 'actual' => 93, 'achv' => 100],
                    'w2' => ['plan' => 91, 'actual' => 98, 'achv' => 100],
                    'w3' => ['plan' => 93, 'actual' => 99, 'achv' => 100],
                    'w4' => ['plan' => 91, 'actual' => 80, 'achv' => 88],
                    'w5' => ['plan' => 93, 'actual' => 95, 'achv' => 100],
                    'trend' => ['plan_mtd' => 92, 'actual' => 93, 'achv' => 100],
                    'monthly' => ['budget_running' => 92, 'actual' => 93, 'achv' => 100],
                ],
            ],
        ];

        // 2. Data Breakdown Type BD & Down Status (Sesuai Gambar 2)
        $breakdownSummary = [
            'equipment_title' => 'EXCAVATOR',
            'type_bd' => [
                'items' => [
                    ['label' => 'B/D schedule', 'hrs' => 18, 'pct' => 5],
                    ['label' => 'B/D unschedule', 'hrs' => 319, 'pct' => 95],
                    ['label' => 'Accident', 'hrs' => 0, 'pct' => 0],
                ],
                'total_hrs' => 337,
                'total_pct' => 100,
            ],
            'down_status' => [
                'items' => [
                    ['code' => 'B0', 'label' => 'On progress', 'hrs' => 75, 'pct' => 22],
                    ['code' => 'B1', 'label' => 'Waiting parts', 'hrs' => 75, 'pct' => 22],
                    ['code' => 'B2', 'label' => 'Waiting sarana', 'hrs' => 0, 'pct' => 0],
                    ['code' => 'B3', 'label' => 'Waiting tools', 'hrs' => 0, 'pct' => 0],
                    ['code' => 'B4', 'label' => 'Waiting Man power', 'hrs' => 0, 'pct' => 0],
                    ['code' => 'B5', 'label' => 'Outside /Dealler', 'hrs' => 186, 'pct' => 55],
                    ['code' => 'B6', 'label' => 'Production/ abuse', 'hrs' => 0, 'pct' => 0],
                    ['code' => 'B7', 'label' => 'W/decision Plant', 'hrs' => 0, 'pct' => 0],
                    ['code' => 'B8', 'label' => 'W/decision HO', 'hrs' => 0, 'pct' => 0],
                ],
                'total_hrs' => 336,
                'total_pct' => 100,
            ],
        ];

        // 3. Data MTBF Bulldozer (Sesuai Gambar 3)
        $mtbfBulldozer = [
            'title' => 'MTBF BULLDOZER',
            'target' => 80,
            'items' => [
                ['unit' => 'MDT006', 'actual' => 0, 'target' => 80],
                ['unit' => 'MDT009', 'actual' => 0, 'target' => 80],
                ['unit' => 'MDT012', 'actual' => 415, 'target' => 80],
                ['unit' => 'MDT015', 'actual' => 261, 'target' => 80],
                ['unit' => 'MDT016', 'actual' => 339, 'target' => 80],
                ['unit' => 'MDT017', 'actual' => 155, 'target' => 80],
                ['unit' => 'MDT019', 'actual' => 209, 'target' => 80],
                ['unit' => 'MDT020', 'actual' => 356, 'target' => 80],
                ['unit' => 'MDT021', 'actual' => 271, 'target' => 80],
                ['unit' => 'MDT022', 'actual' => 355, 'target' => 80],
                ['unit' => 'MDT023', 'actual' => 288, 'target' => 80],
                ['unit' => 'MDT025', 'actual' => 142, 'target' => 80],
                ['unit' => 'MDT026', 'actual' => 20, 'target' => 80],
                ['unit' => 'MDT027', 'actual' => 254, 'target' => 80],
                ['unit' => 'MDT028', 'actual' => 231, 'target' => 80],
                ['unit' => 'MDT029', 'actual' => 393, 'target' => 80],
                ['unit' => 'MDT035', 'actual' => 407, 'target' => 80],
            ],
        ];

        // 4. Data MTTR Bulldozer (Sesuai Gambar 4)
        $mttrBulldozer = [
            'title' => 'MTTR BULLDOZER',
            'target' => 15,
            'items' => [
                ['unit' => 'MDT006', 'actual' => 3, 'target' => 15],
                ['unit' => 'MDT009', 'actual' => 1, 'target' => 15],
                ['unit' => 'MDT012', 'actual' => 25, 'target' => 15],
                ['unit' => 'MDT015', 'actual' => 65, 'target' => 15],
                ['unit' => 'MDT016', 'actual' => 27, 'target' => 15],
                ['unit' => 'MDT017', 'actual' => 141, 'target' => 15],
                ['unit' => 'MDT019', 'actual' => 273, 'target' => 15],
                ['unit' => 'MDT020', 'actual' => 48, 'target' => 15],
                ['unit' => 'MDT021', 'actual' => 48, 'target' => 15],
                ['unit' => 'MDT022', 'actual' => 113, 'target' => 15],
                ['unit' => 'MDT023', 'actual' => 58, 'target' => 15],
                ['unit' => 'MDT025', 'actual' => 60, 'target' => 15],
                ['unit' => 'MDT026', 'actual' => 0, 'target' => 15],
                ['unit' => 'MDT027', 'actual' => 36, 'target' => 15],
                ['unit' => 'MDT028', 'actual' => 69, 'target' => 15],
                ['unit' => 'MDT029', 'actual' => 33, 'target' => 15],
                ['unit' => 'MDT030', 'actual' => 744, 'target' => 15],
                ['unit' => 'MDT035', 'actual' => 11, 'target' => 15],
                ['unit' => 'MDT036', 'actual' => 390, 'target' => 15],
                ['unit' => 'MDT039', 'actual' => 58, 'target' => 15],
                ['unit' => 'MDT040', 'actual' => 2, 'target' => 15],
                ['unit' => 'MDT041', 'actual' => 690, 'target' => 15],
                ['unit' => 'MDT042', 'actual' => 123, 'target' => 15],
                ['unit' => 'MDT043', 'actual' => 47, 'target' => 15],
                ['unit' => 'MDT045', 'actual' => 153, 'target' => 15],
                ['unit' => 'MDT046', 'actual' => 5, 'target' => 15],
                ['unit' => 'MDT047', 'actual' => 10, 'target' => 15],
            ],
        ];

        // 5. Data Pareto Komponen (Sesuai Gambar 5)
        $paretoDuration = [
            'title' => 'Pareto Excavator Big Digger Pareto berdasarkan duration',
            'equipment' => 'EXCAVATOR BIG DIGGER',
            'items' => [
                ['component' => 'AC SYSTEM', 'duration' => 143],
                ['component' => 'ACCIDENT', 'duration' => 0],
                ['component' => 'AIR SYSTEM', 'duration' => 148],
                ['component' => 'ATTACHMENT', 'duration' => 216],
                ['component' => 'AUTOLUBE', 'duration' => 5],
                ['component' => 'BATTERY', 'duration' => 55],
                ['component' => 'BLADE', 'duration' => 9],
                ['component' => 'BRAKE SYSTEM', 'duration' => 70],
                ['component' => 'BUCKET', 'duration' => 0],
                ['component' => 'CABIN', 'duration' => 36],
                ['component' => 'CLUTCH', 'duration' => 174],
                ['component' => 'COOLING SYSTEM', 'duration' => 0],
                ['component' => 'DAMPER', 'duration' => 0],
                ['component' => 'DIFFERENTIAL', 'duration' => 0],
                ['component' => 'ELECTRIC SYSTEM', 'duration' => 596],
                ['component' => 'ENGINE', 'duration' => 313],
                ['component' => 'FINAL DRIVE', 'duration' => 0],
                ['component' => 'FRAME/BODY/GUARD/CHASSIS', 'duration' => 16],
                ['component' => 'FUEL SYSTEM', 'duration' => 67],
                ['component' => 'GET', 'duration' => 7],
                ['component' => 'HOSES', 'duration' => 189],
                ['component' => 'HYDRAULIC SYSTEM', 'duration' => 4],
                ['component' => 'LEVEL OIL/COOLANT', 'duration' => 257],
                ['component' => 'PROPELLER SHAFT', 'duration' => 125],
                ['component' => 'PTO', 'duration' => 43],
                ['component' => 'RADIATOR', 'duration' => 7],
                ['component' => 'RADIO', 'duration' => 173],
                ['component' => 'REAR AXLE', 'duration' => 5],
                ['component' => 'STEERING SYSTEM', 'duration' => 0],
                ['component' => 'SUSPENSION', 'duration' => 20],
                ['component' => 'SWING', 'duration' => 302],
                ['component' => 'TAIL GATE', 'duration' => 0],
                ['component' => 'TRANSMISSION', 'duration' => 0],
                ['component' => 'TYRE', 'duration' => 439],
                ['component' => 'UNDERCARRIAGE', 'duration' => 1833],
                ['component' => 'VESSEL', 'duration' => 81],
                ['component' => 'WASHING', 'duration' => 9],
                ['component' => 'WATER CANON/SPRAYER', 'duration' => 0],
                ['component' => 'WHEEL & HUB', 'duration' => 58],
            ],
        ];

        // 6. Data Pareto Berdasarkan Event Excavator Big Digger (Gambar Tambahan 1)
        $paretoEvent = [
            'title' => 'Pareto berdasarkan Event Excavator Big Digger',
            'equipment' => 'EXCAVATOR BIG DIGGER',
            'items' => [
                ['component' => 'AC SYSTEM', 'events' => 20],
                ['component' => 'ACCESSORIES', 'events' => 0],
                ['component' => 'ACCIDENT', 'events' => 0],
                ['component' => 'AIR SYSTEM', 'events' => 27],
                ['component' => 'ATTACHMENT', 'events' => 2],
                ['component' => 'AUTOLUBE', 'events' => 22],
                ['component' => 'BATTERY', 'events' => 44],
                ['component' => 'BLADE', 'events' => 8],
                ['component' => 'BRAKE SYSTEM', 'events' => 38],
                ['component' => 'BUCKET', 'events' => 0],
                ['component' => 'CABIN', 'events' => 2],
                ['component' => 'CLUTCH', 'events' => 66],
                ['component' => 'COOLING SYSTEM', 'events' => 1],
                ['component' => 'DAMPER', 'events' => 0],
                ['component' => 'DIFFERENTIAL', 'events' => 1],
                ['component' => 'ELECTRIC SYSTEM', 'events' => 61],
                ['component' => 'ENGINE', 'events' => 6],
                ['component' => 'FINAL DRIVE', 'events' => 0],
                ['component' => 'FRAME/BODY/GUARD/CHASSIS', 'events' => 8],
                ['component' => 'FRONT AXLE', 'events' => 6],
                ['component' => 'FUEL SYSTEM', 'events' => 52],
                ['component' => 'GET', 'events' => 12],
                ['component' => 'GREASING', 'events' => 314],
                ['component' => 'HOSES', 'events' => 106],
                ['component' => 'HYDRAULIC SYSTEM', 'events' => 0],
                ['component' => 'INTAKE & EXHAUST SYSTEM', 'events' => 8],
                ['component' => 'LEVEL OIL/COOLANT', 'events' => 106],
                ['component' => 'MAINTENANCE/SERVICE', 'events' => 74],
                ['component' => 'PROPELLER SHAFT', 'events' => 15],
                ['component' => 'PTO', 'events' => 4],
                ['component' => 'RADIATOR', 'events' => 26],
                ['component' => 'RADIO', 'events' => 10],
                ['component' => 'REAR AXLE', 'events' => 0],
                ['component' => 'STEERING SYSTEM', 'events' => 7],
                ['component' => 'SUSPENSION', 'events' => 7],
                ['component' => 'SWING', 'events' => 0],
                ['component' => 'TAIL GATE', 'events' => 0],
                ['component' => 'TRANSMISSION', 'events' => 51],
                ['component' => 'TYRE', 'events' => 33],
                ['component' => 'UNDERCARRIAGE', 'events' => 11],
                ['component' => 'VESSEL', 'events' => 2],
                ['component' => 'WASHING', 'events' => 0],
                ['component' => 'WATER CANON/SPRAYER', 'events' => 1],
                ['component' => 'WHEEL & HUB', 'events' => 2],
            ],
        ];

        // 7. Data Klasifikasi Unit Breakdown Excavator Big Digger (Gambar Tambahan 2)
        $klasifikasiBreakdown = [
            'title' => 'Klasifikasi Unit Breakdown Excavator Big Digger',
            'items' => [
                ['no' => 1, 'unit' => 'ME049', 'problem' => 'Hose boom cylinder pecah bocor oli hydraulic', 'action' => 'Penggantian hose hydraulic & top up oil', 'downtime' => '4.5 Jam', 'status' => 'COMPLETED'],
                ['no' => 2, 'unit' => 'ME055', 'problem' => 'Greasing autolube buntu pada pin bucket', 'action' => 'Cleaning nipple & pembersihan jalur greasing', 'downtime' => '2.0 Jam', 'status' => 'COMPLETED'],
                ['no' => 3, 'unit' => 'ME056', 'problem' => 'Level coolant radiator low & warning alarm buzzer', 'action' => 'Inspeksi kebocoran water pump & refilling coolant', 'downtime' => '1.5 Jam', 'status' => 'COMPLETED'],
                ['no' => 4, 'unit' => 'ME049', 'problem' => 'Track shoe baut kendor sebelah kiri & tensioner kendor', 'action' => 'Tightening track shoe bolt & grease track adjuster', 'downtime' => '3.5 Jam', 'status' => 'COMPLETED'],
                ['no' => 5, 'unit' => 'ME055', 'problem' => 'Wiring harness starter kendor tidak bisa start', 'action' => 'Repair terminal starter & cleaning konektor alternator', 'downtime' => '2.5 Jam', 'status' => 'COMPLETED'],
                ['no' => 6, 'unit' => 'ME056', 'problem' => 'O-ring hose pilot valve rembes oli', 'action' => 'Penggantian O-ring seal pilot control valve', 'downtime' => '3.0 Jam', 'status' => 'COMPLETED'],
                ['no' => 7, 'unit' => 'ME049', 'problem' => 'Periodical Service 500 Jam (PM Service)', 'action' => 'Ganti oli engine, filter oli, fuel filter & general check', 'downtime' => '5.0 Jam', 'status' => 'COMPLETED'],
                ['no' => 8, 'unit' => 'ME055', 'problem' => 'Air cleaner indikator clog & debu pekat', 'action' => 'Blowing & penggantian outer air filter', 'downtime' => '1.0 Jam', 'status' => 'COMPLETED'],
            ],
        ];

        return Inertia::render('Kpi/Index', [
            'month' => $month,
            'targetPa' => $paPlan,
            'paUnitMatrix' => $paUnitMatrix,
            'breakdownSummary' => $breakdownSummary,
            'mtbfBulldozer' => $mtbfBulldozer,
            'mttrBulldozer' => $mttrBulldozer,
            'paretoDuration' => $paretoDuration,
            'paretoEvent' => $paretoEvent,
            'klasifikasiBreakdown' => $klasifikasiBreakdown,
        ]);
    }
}
